# shallow clone
clone_depth: 5

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

install:
  - git submodule update --init --recursive
  - cd externals
  - git clone https://github.com/citra-emu/ext-boost boost
  - cd ..

before_build:
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DDYNARMIC_USE_SYSTEM_BOOST=0 -DBoost_INCLUDE_DIRS=externals/boost
  - cd ..

build:
  project: build/dynarmic.sln
  parallel: true

test_script:
  - cd build && ctest -VV -C Release && cd ..
